theme: jekyll-theme-minimal
google_analytics: UA-142462751-1
title: ატხადნიაკი
description: დაუვიწყარი ბედნიერებით სავსე ღამის გატარების საფასურს ხშირად დაუვიწყარი უბედურებით სავსე დღით ვიხდით. მაგრამ აუცილებელი არაა ასე ხდებოდეს. ამ გვერდზე მოკლედ ავხსნი, როგორ ავარიდოთ თავი გართობის მერე ფიზიკურ და ფსიქოლოგიურ დისკომფორტს.
