#+TITLE: atxadniaki
#+OPTIONS: toc:nil \n:t h:4

თუ სულ რამდენიმე წამის გატარებას აპირებ აქ, Table of contents-ში ყველაფერი წერია, რაც გჭირდება. ქვემოთ უფრო მეტი დეტალი და ახსნაა თითოეულ საკითხზე. ბოლოს, ჩემი აზრით საინტერესოა იმის გააზრებაც, რა მექანიზმი მუშაობს ამ ყველაფრის მიღმა.

#+TOC: headlines 4
* როგორ დავიცვათ თავი უარყოფითი ეფექტებისგან
-----
** გართობამდე დღისით და საღამოს
**** მსუბუქად და ჯანსაღად კვება
მეტწილად ხილით და ბოსტნეულით კვება
**** c ვიტამინი (1000მგ), მაგნეზიუმი (250მგ)
** ღამით
**** ბევრი სითხეები
  წყალზე ყველამ იცის, მაგრამ მარტო ეგ საკმარისი არ არის. ბორჯომი, ფორთოხლის წვენიც დალიე პერიოდულად.
**** თუ გშია - მსუბუქი მაგრამ მაღალკალორიული საკვები
  მაგალითად ჩირი და თხილი. რო რამე დამუშავებული შაქრის შემცველი პროდუქტებიც წავა (ჟელიბონი და ა.შ) ასეთი საკვები იმის გამოა უკეთესი, რომ  საჭმლის მონელების თასქი არ ემატება ისედაც უთვალავ საქმეს.
**** ცეკვისგან და სიარულისგან ხშირად დასვენება
  მოდუნების ნაკლებობა კუნთების გადაღლას იწვევს, რაც შემდეგ დაკავშირებულია სისუსტესთან, კანკალთან და ჟანგბადის ათვისებაში შეფერხებასთან.

რა თქმა უნდა, ყველაფრის კონტროლი არც ისე სასიამოვნო ან სახალისოა და უმეტესად თვითონ ვგრძნობთ როდის გვჭირდება პაუზა. შეუძლებელია დასვენების დროები 'დაგეგმო'. უბრალოდ, უფრო ყურადღებით იყავი  და გახსოვდეს, რომ შენი ან მეგობრის შეუძლოდ ყოფნას დასვენებით, სითხეებით და ენერგიული საჭმლით შეგიძლია უშველო.
** დილას
**** c ვიტამინი, მაგნეზიუმი
გუშინ მიღებული დენსფლორზე დარჩა :)
**** 5htp
ანტიდეპრესანტია და სერატონინის ნაკლებობით გამოწვეულ ცუდ ხასიათს შველის.
** შემდეგი დღეები
**** ძილი და დასვენება
გართობას (ან მუშაობას) ჩვენი ფიზიკური და ფსიქიკური ჯანმრთელობა არ უნდა შევწიროთ. კუნთების და ტვინის გადაღლას ბევრი დაუყოვნებლივი და გრძელვადიანი ზიანი მოაქვს და ჯანსაღი და საკმარისი ძილი რეაბილიტაციისთვის აუცილებელია.
**** საკმარისი ჭამა
ენერგიის გარეშე შემთხვევაში ორგანიზმი კიდევ უფრო დასუსტდება, ამიტომ საკვებზე შეზღუდვები ცოტა ხანი დაიკიდე.
** სხვა ვიტამინები წინა და შემდეგ კვირებში
ცე და მაგნეზიუმი უმეტეს შემთხვევაში ყველაზე აქტიურად იხარჯება და უპირობოდ აუცილებელია, მაგრამ მათ გარდა სხვა ნივთიერებების მომარაგება და აღდგენაც კარგი აზრია. ყველაზე მარტივი გზა არის აფთიაქში ომეგას, კალციუმების მიქსის (მაგალითად CalciCare) და მულტივიტამინის ყიდვა და დღეში 1-2ჯერ ჭამის მერე დალევა.
* რა იწვევს ამ ყველაფერს
-----
- ხანგრძლივი დროით აქტიურობის და უცხო ნივთიერების მიღებისას ორგანიზმი ზედმეტად იტვირთვება, ერთდროულად ბევრი ქიმიური და ბიოლოგიური პროცესის მართვა უწევს, და ამ ყველაფერთან გამკლავებას ძილის გარეშე ახერხებს
- ეს პროცესები დიდი რაოდენობით ვიტამინებს და რესურსებს მოითხოვს, და მათი გამოლევის შემდეგ ყველაზე ელემენტარული ფუნქციების რეგულირებაც კი შეუძლებელი ხდება ორგანიზმისთვის.
- ამ ყველაფრის შედეგად ორგანიზმი დიდ სტრესს განიცდის, რაც საბოლოოდ ცუდ ფიზიკურ შეგრძნებებს, შფოთვას, უიმედო, უხასიათო და ზოგჯერ აგრესიულ განწყობას იწვევს. გარდა ამისა, ხშირ შემთხვევაში გართობისას მიღებული ნივთიერებები პირდაპირ ბედნიერების ჰორმონების დაცლას იწვევენ, რაც ცუდ განწყობას კიდევ უფრო ამძაფრებს.

  ნებისმიერ შედეგთან საბრძოლველად ორი გზა არსებობს: თავის არიდება და გამოწვეული ზიანის ანაზღაურება. ამ შემთხვევაში ორივე საჭიროა - ძლიერი ორგანიზმი უფრო ნაკლები ზიანით დაასრულებს ღამეს, მაგრამ რაც არ უნად სრულყოფილად ჯანმრთელი იყო, ზარალი მაინც იქნება და დილას მასთან გამკლავებისთვის დახმარებაა საჭირო.
