#+TITLE: atxadniaki
#+OPTIONS: toc:2 \n:t
* რა იწვევს ატხადნიაკს
- ხანგრძლივი დროით აქტიურობის და უცხო ნივთიერების მიღებისას ორგანიზმი ზედმეტად იტვირთვება, ერთდროულად ბევრი ქიმიური და ბიოლოგიური პროცესის მართვა უწევს, და ამ ყველაფერთან გამკლავებას ძილის გარეშე ახერხებს
- ეს პროცესები დიდი რაოდენობით ვიტამინებს და რესურსებს მოითხოვს, და მათი გამოლევის შემდეგ ყველაზე ელემენტარული ფუნქციების რეგულირებაც კი შეუძლებელი ხდება ორგანიზმისთვის.
- ამ ყველაფრის შედეგად ორგანიზმი დიდ სტრესს განიცდის, რაც საბოლოოდ ცუდ ფიზიკურ შეგრძნებებს, შფოთვას, უიმედო, უხასიათო და ზოგჯერ აგრესიულ განწყობას იწვევს. გარდა ამისა, ხშირ შემთხვევაში გართობისას მიღებული ნივთიერებები პირდაპირ ბედნიერების ჰორმონების დაცლას იწვევენ, რაც ცუდ განწყობას კიდევ უფრო ამძაფრებს.

  ნებისმიერ შედეგთან საბრძოლველად ორი გზა არსებობს: თავის არიდება და გამოწვეული ზიანის ანაზღაურება. ამ შემთხვევაში ორივე საჭიროა - ძლიერი ორგანიზმი უფრო ნაკლები ზიანით დაასრულებს ღამეს, მაგრამ რაც არ უნად სრულყოფილად ჯანმრთელი იყო, ზარალი მაინც იქნება და დილას მასთან გამკლავებისთვის დახმარებაა საჭირო.
* რა დაგვეხმარება
** გართობამდე დღისით და საღამოს
- მსუბუქად, მეტწილად ხილით და ბოსტნეულით კვება
- c ვიტამინი (1000მგ), მაგნეზიუმი (250მგ)
** ღამით
- ბევრი წყალი, მაგრამ მარტო წყალიც არაა კარგი, ბორჯომი, ფორთოხლის წვენიც პერიოდულად.
- თუ გშია, მსუბუქი მაგრამ მაღალკალორიული საკვების მიღება სჯობს  
  მაგალითად ჩირი და თხილი. რო რამე დამუშავებული შაქრის შემცველი პროდუქტებიც წავა (ჟელიბონი და ა.შ) ასეთი საკვები იმის გამოა უკეთესი, რომ  საჭმლის მონელების თასქი არ ემატება ისედაც უთვალავ საქმეს.
- ცეკვისგან და სიარულისგან ხშირად დასვენება
  მოდუნების ნაკლებობა კუნთების გადაღლას იწვევს, რაც შემდეგ დაკავშირებულია სისუსტესთან, კანკალთან და არასრულფასოვან სუნთქვასთან.

რა თქმა უნდა, ყველაფრის კონტროლი არც ისე სასიამოვნო ან სახალისოა და უმეტესად თვითონ ვგრძნობთ როდის გვჭირდება პაუზა. შეუძლებელია დასვენების დროები 'დაგეგმო', უბრალოდ უფრო ყურადღებით იყავი შინაგან გრძნობებთან და გახსოვდეს, რომ შენი ან მეგობრის შეუძლოდ ყოფნას დასვენებით, სითხეებით და ენერგიული საჭმლით შეგიძლია უშველო.
** დილას
- c ვიტამინი, მაგნეზიუმი. გუშინ მიღებული დენსფლორზე დარჩა :)
- 5htp. ანტიდეპრესანტია და სერატონინის ნაკლებობით გამოწვეულ ცუდ ხასიათს შველის.
** შემდეგი დღეები
*** ძილი და დასვენება
გართობას (ან მუშაობას) ჩვენი ფიზიკური და ფსიქიკური ჯანმრთელობა არ უნდა შევწიროთ. კუნთების და ტვინის გადაღლას ბევრი დაუყოვნებლივი და გრძელვადიანი ზიანი მოაქვს და ჯანსაღი და საკმარისი ძილი რეაბილიტაციისთვის აუცილებელია.
*** საკმარისი ჭამა
ენერგიის გარეშე შემთხვევაში ორგანიზმი კიდევ უფრო დასუსტდება, ამიტომ საკვებზე შეზღუდვები ცოტა ხანი დაიკიდე.
** სხვა ვიტამინები წინა და შემდეგ კვირებში
ცე და მაგნეზიუმი უმეტეს შემთხვევაში ყველაზე აქტიურად იხარჯება და უპირობოდ აუცილებელია, მაგრამ მათ გარდა სხვა ნივთიერებების მომარაგება და აღდგენაც კარგი აზრია. ყველაზე მარტივი გზა არის აფთიაქში ომეგას, კალციუმების მიქსის (მაგალითად CalciCare) და მულტივიტამინის ყიდვა და დღეში 1-2ჯერ ჭამის მერე დალევა.
